name: Create Release on Merge

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Determine version
        id: version
        run: |
          # Check if any tags exist; if not, use a default initial version
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "")
          if [[ -z "$latest_tag" ]]; then
            new_version="v1.0.0"
          else
            # Assume a semver tag format and increment the patch version
            new_version=$(echo $latest_tag | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          fi
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          release_name: Release v${{ steps.version.outputs.new_version }}
          body: "Automated release generated on merge to main"
          draft: false
          prerelease: false
